GET http://localhost:8000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ3LCJ1c2VybmFtZSI6Im1lc3NhZ2UiLCJpYXQiOjE2NDA3NTU5MTYsImV4cCI6MTY0MDkyODcxNn0.JwNNDs3HXy40ZzxyhEyl60Pjx2f7r_W97P_GXyKr9cU